import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import { Main } from '@/components/imports'
import { sanityClient } from '@/config/client'

const inter = Inter({ subsets: ['latin'] })

export default function Home({university}) {
  
  return (
    <>
      <Head>
        <title>Slearn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Main data={university}/>
    </>
  )
}



export const getServerSideProps = async (pageContext) => {
  const query = ` *[ _type == "university"]{
    university_name,
    slug,
    icon{
      asset->{
        url
      }
    }
  }`;

  const university = await sanityClient.fetch(query);
  return {
    props: {
      university
    },
  }
}; 

